// GENERATED by sync.py — do not hand-edit.
export type TimelineEntry = {scene: string; from: number; duration: number; props?: Record<string, unknown>};
export const timeline: TimelineEntry[] = [
  {scene: "01-call", from: 0, duration: 425},
  {scene: "02-solution", from: 425, duration: 696},
  {scene: "03-opportunity", from: 1121, duration: 425},
  {scene: "04-value", from: 1546, duration: 701},
  {scene: "05-watch", from: 2247, duration: 513},
  {scene: "06-routine", from: 2760, duration: 2725},
  {scene: "07-evidence-limits", from: 5485, duration: 525},
  {scene: "08-other-paths", from: 6010, duration: 237},
  {scene: "09-question", from: 6247, duration: 474},
  {scene: "10-team-rules", from: 6721, duration: 614},
  {scene: "11-implementation", from: 7335, duration: 679},
  {scene: "12-decision", from: 8014, duration: 986},
];
export const voFile: string | null = null;
