"use client";

import { useState, useCallback } from "react";
import { FileDown, Printer, RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { Currency, ExchangeRates } from "@/lib/currency";
import { convertCurrency, formatCurrency } from "@/lib/currency";
import { EFFICIENCY, TIERS, PACKAGES, ADDONS } from "@/lib/calculator-data";

interface PDFExportProps {
  hours: number;
  rate: number;
  setupCost: number;
  selectedAutomations: Set<string>;
  selectedAddOns: Set<string>;
  selectedPackage: string | null;
  currency: Currency;
  rates: ExchangeRates;
  onReset: () => void;
}

function PDFExport({
  hours,
  rate,
  setupCost,
  selectedAutomations,
  selectedAddOns,
  selectedPackage,
  currency,
  rates,
  onReset,
}: PDFExportProps) {
  const [companyName, setCompanyName] = useState("");
  const [isExporting, setIsExporting] = useState(false);

  const fmt = useCallback(
    (usd: number) => formatCurrency(convertCurrency(usd, rates, currency), currency),
    [rates, currency],
  );

  const generateHTML = useCallback(() => {
    const weeklyCost = hours * rate;
    const annualCost = weeklyCost * 52;
    const automatedHours = hours * EFFICIENCY;
    const remainingHours = hours - automatedHours;
    const annualAfter = remainingHours * rate * 52;
    const annualSavings = annualCost - annualAfter;
    const weeklySavings = annualSavings / 52;
    const breakEvenWeeks = weeklySavings > 0 ? Math.ceil(setupCost / weeklySavings) : Infinity;
    const yearOneROI = annualSavings - setupCost;
    const roiPercent = setupCost > 0 ? Math.round((yearOneROI / setupCost) * 100) : 0;

    const selectedAutomationsList = Array.from(selectedAutomations)
      .map((name) => {
        for (const tier of Object.values(TIERS)) {
          const found = tier.automations.find((a) => a.name === name);
          if (found) return { name: found.name, price: found.price };
        }
        return null;
      })
      .filter(Boolean);

    const selectedAddonsList = ADDONS.filter((a) => selectedAddOns.has(a.name));
    const pkg = selectedPackage ? PACKAGES.find((p) => p.name === selectedPackage) : null;

    const title = companyName ? `${companyName} — ROI Report` : "ROI Report";

    return `
      <div style="font-family: 'Inter', -apple-system, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #37322F;">
        <!-- Header -->
        <div style="text-align: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 2px solid #F0EDEB;">
          <h1 style="font-size: 28px; font-weight: 600; margin: 0 0 8px;">${title}</h1>
          <p style="font-size: 14px; color: #605A57; margin: 0;">Generated by FlowAudit &bull; ${new Date().toLocaleDateString()}</p>
        </div>

        <!-- ROI Summary -->
        <div style="margin-bottom: 32px;">
          <h2 style="font-size: 18px; font-weight: 600; margin-bottom: 16px;">ROI Summary</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr style="border-bottom: 1px solid #F0EDEB;">
              <td style="padding: 8px 0; color: #605A57; font-size: 14px;">Manual Hours/Week</td>
              <td style="padding: 8px 0; text-align: right; font-weight: 600; font-size: 14px;">${hours} hrs</td>
            </tr>
            <tr style="border-bottom: 1px solid #F0EDEB;">
              <td style="padding: 8px 0; color: #605A57; font-size: 14px;">Hourly Rate</td>
              <td style="padding: 8px 0; text-align: right; font-weight: 600; font-size: 14px;">${fmt(rate)}</td>
            </tr>
            <tr style="border-bottom: 1px solid #F0EDEB;">
              <td style="padding: 8px 0; color: #605A57; font-size: 14px;">Annual Cost (Before)</td>
              <td style="padding: 8px 0; text-align: right; font-weight: 600; font-size: 14px;">${fmt(annualCost)}</td>
            </tr>
            <tr style="border-bottom: 1px solid #F0EDEB;">
              <td style="padding: 8px 0; color: #605A57; font-size: 14px;">Annual Cost (After)</td>
              <td style="padding: 8px 0; text-align: right; font-weight: 600; font-size: 14px;">${fmt(annualAfter)}</td>
            </tr>
            <tr style="border-bottom: 1px solid #F0EDEB;">
              <td style="padding: 8px 0; color: #605A57; font-size: 14px;">Annual Savings</td>
              <td style="padding: 8px 0; text-align: right; font-weight: 600; font-size: 14px; color: #059669;">${fmt(annualSavings)}</td>
            </tr>
            <tr style="border-bottom: 1px solid #F0EDEB;">
              <td style="padding: 8px 0; color: #605A57; font-size: 14px;">Setup Investment</td>
              <td style="padding: 8px 0; text-align: right; font-weight: 600; font-size: 14px;">${fmt(setupCost)}</td>
            </tr>
            <tr style="border-bottom: 1px solid #F0EDEB;">
              <td style="padding: 8px 0; color: #605A57; font-size: 14px;">Break-Even</td>
              <td style="padding: 8px 0; text-align: right; font-weight: 600; font-size: 14px;">${breakEvenWeeks === Infinity ? "N/A" : `${breakEvenWeeks} weeks`}</td>
            </tr>
            <tr style="border-bottom: 2px solid #37322F;">
              <td style="padding: 12px 0; font-weight: 600; font-size: 16px;">Year 1 Net ROI</td>
              <td style="padding: 12px 0; text-align: right; font-weight: 700; font-size: 16px; color: ${yearOneROI >= 0 ? "#059669" : "#dc2626"};">${fmt(yearOneROI)} (${roiPercent}%)</td>
            </tr>
          </table>
        </div>

        <!-- Selected Package or Automations -->
        ${
          pkg
            ? `
          <div style="margin-bottom: 32px;">
            <h2 style="font-size: 18px; font-weight: 600; margin-bottom: 16px;">Selected Package: ${pkg.name}</h2>
            <p style="font-size: 14px; color: #605A57;">${pkg.description} — ${fmt(pkg.price)}</p>
            <ul style="margin-top: 8px; padding-left: 20px;">
              ${pkg.features.map((f) => `<li style="font-size: 13px; color: #605A57; margin-bottom: 4px;">${f}</li>`).join("")}
            </ul>
          </div>
        `
            : selectedAutomationsList.length > 0
              ? `
          <div style="margin-bottom: 32px;">
            <h2 style="font-size: 18px; font-weight: 600; margin-bottom: 16px;">Selected Automations (${selectedAutomationsList.length})</h2>
            <table style="width: 100%; border-collapse: collapse;">
              ${selectedAutomationsList.map((a) => (a ? `<tr style="border-bottom: 1px solid #F0EDEB;"><td style="padding: 6px 0; font-size: 13px;">${a.name}</td><td style="padding: 6px 0; text-align: right; font-size: 13px; color: #605A57;">${fmt(a.price)}</td></tr>` : "")).join("")}
            </table>
          </div>
        `
              : ""
        }

        <!-- Add-ons -->
        ${
          selectedAddonsList.length > 0
            ? `
          <div style="margin-bottom: 32px;">
            <h2 style="font-size: 18px; font-weight: 600; margin-bottom: 16px;">Add-On Services</h2>
            <table style="width: 100%; border-collapse: collapse;">
              ${selectedAddonsList.map((a) => `<tr style="border-bottom: 1px solid #F0EDEB;"><td style="padding: 6px 0; font-size: 13px;">${a.name}</td><td style="padding: 6px 0; text-align: right; font-size: 13px; color: #605A57;">${fmt(a.price)}</td></tr>`).join("")}
            </table>
          </div>
        `
            : ""
        }

        <!-- Footer -->
        <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #F0EDEB; text-align: center;">
          <p style="font-size: 12px; color: #605A57;">FlowAudit &bull; flowaudit.co.uk &bull; AI Operations Assistants</p>
          <p style="font-size: 11px; color: #605A57; margin-top: 4px;">This report is an estimate. Actual results may vary based on implementation scope.</p>
        </div>
      </div>
    `;
  }, [
    hours,
    rate,
    setupCost,
    selectedAutomations,
    selectedAddOns,
    selectedPackage,
    companyName,
    fmt,
  ]);

  const handleExportPDF = useCallback(async () => {
    setIsExporting(true);
    let iframe: HTMLIFrameElement | null = null;
    try {
      const html2pdf = (await import("html2pdf.js")).default;

      // Use an iframe to isolate from Tailwind's oklch() colors
      // (html2canvas cannot parse oklch, which Tailwind v4 uses)
      iframe = document.createElement("iframe");
      iframe.style.position = "fixed";
      iframe.style.left = "-9999px";
      iframe.style.top = "-9999px";
      iframe.style.width = "800px";
      iframe.style.height = "1200px";
      document.body.appendChild(iframe);

      const iframeDoc = iframe.contentDocument;
      if (!iframeDoc) throw new Error("Could not access iframe document");

      iframeDoc.open();
      iframeDoc.write(`<!DOCTYPE html>
        <html style="color:#37322F;background:#fff;"><head>
          <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
          <style>
            /* Reset all colors to simple hex values so html2canvas
               never encounters lab()/oklch() from browser system colors */
            *, *::before, *::after {
              color: inherit;
              border-color: #F0EDEB;
              outline-color: #37322F;
              text-decoration-color: inherit;
              column-rule-color: inherit;
              caret-color: auto;
            }
            html, body {
              color: #37322F;
              background-color: #ffffff;
            }
          </style>
        </head><body style="margin:0;padding:0;">
          ${generateHTML()}
        </body></html>`);
      iframeDoc.close();

      // Allow fonts and content to render
      await new Promise((resolve) => setTimeout(resolve, 500));

      const content = iframeDoc.body.firstElementChild as HTMLElement | null;
      if (!content) throw new Error("PDF content failed to render");

      await html2pdf()
        .set({
          margin: [10, 10, 10, 10],
          filename: `${companyName || "FlowAudit"}-ROI-Report.pdf`,
          image: { type: "jpeg", quality: 0.98 },
          html2canvas: {
            scale: 2,
            backgroundColor: "#ffffff",
            // Sanitize cloned DOM so html2canvas never encounters
            // unsupported color functions (lab, oklch) from browser system colors
            onclone: (clonedDoc: Document) => {
              const colorProps = [
                "color",
                "backgroundColor",
                "borderColor",
                "borderTopColor",
                "borderRightColor",
                "borderBottomColor",
                "borderLeftColor",
                "outlineColor",
                "textDecorationColor",
                "columnRuleColor",
                "caretColor",
                "accentColor",
              ] as const;
              const unsupported = /\b(lab|oklch|lch|oklab)\(/i;
              for (const el of clonedDoc.querySelectorAll("*")) {
                const style = clonedDoc.defaultView?.getComputedStyle(el);
                if (!style) continue;
                for (const prop of colorProps) {
                  const val = style[prop];
                  if (typeof val === "string" && unsupported.test(val)) {
                    (el as HTMLElement).style[prop] = prop.includes("ackground")
                      ? "#ffffff"
                      : "#37322F";
                  }
                }
              }
            },
          },
          jsPDF: { unit: "mm", format: "a4", orientation: "portrait" },
        })
        .from(content)
        .save();
    } catch (error) {
      console.error("PDF export failed:", error);
    } finally {
      if (iframe?.parentNode) {
        iframe.parentNode.removeChild(iframe);
      }
      setIsExporting(false);
    }
  }, [generateHTML, companyName]);

  const handlePrint = useCallback(() => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) {
      // Popup blocked — fall back to printing current page
      window.print();
      return;
    }
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>FlowAudit ROI Report</title>
          <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
        </head>
        <body style="margin: 0; padding: 20px;">
          ${generateHTML()}
          <script>window.onload = function() { window.print(); }<\/script>
        </body>
      </html>
    `);
    printWindow.document.close();
  }, [generateHTML]);

  return (
    <div className="rounded-2xl border border-[rgba(55,50,47,0.08)] bg-white p-6">
      <h3 className="mb-1 font-sans text-sm font-semibold text-[#37322F]">Export Report</h3>
      <p className="mb-4 font-sans text-xs text-[#605A57]">
        Your personalized report, ready to share with your team.
      </p>
      <div className="space-y-3">
        <input
          type="text"
          placeholder="Company name (optional)"
          value={companyName}
          onChange={(e) => setCompanyName(e.target.value)}
          className="w-full rounded-lg border border-[rgba(55,50,47,0.12)] bg-white px-3 py-2 font-sans text-sm text-[#37322F] placeholder:text-[#605A57]/50 focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/30 focus:outline-none"
        />
        <div className="flex gap-2">
          <Button
            onClick={handleExportPDF}
            disabled={isExporting}
            className="flex-1 bg-emerald-600 text-white hover:bg-emerald-700"
          >
            <FileDown className="mr-2 h-4 w-4" />
            {isExporting ? "Exporting..." : "Export PDF"}
          </Button>
          <Button onClick={handlePrint} variant="secondary" className="flex-1">
            <Printer className="mr-2 h-4 w-4" />
            Print Report
          </Button>
        </div>
        <Button
          variant="ghost"
          className="w-full border border-dashed border-[rgba(55,50,47,0.2)]"
          onClick={() => {
            onReset();
            setCompanyName("");
          }}
        >
          <RotateCcw className="mr-2 h-4 w-4" />
          Reset Calculator
        </Button>
      </div>
    </div>
  );
}

export { PDFExport };
