"use client";

import { useState, useCallback } from "react";
import { FileDown, Printer, RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { Currency, ExchangeRates } from "@/lib/currency";
import { convertCurrency, formatCurrency } from "@/lib/currency";
import { EFFICIENCY, TIERS, PACKAGES, ADDONS } from "@/lib/calculator-data";

interface PDFExportProps {
  hours: number;
  rate: number;
  setupCost: number;
  selectedAutomations: Set<string>;
  selectedAddOns: Set<string>;
  selectedPackage: string | null;
  currency: Currency;
  rates: ExchangeRates;
  onReset: () => void;
}

function PDFExport({
  hours,
  rate,
  setupCost,
  selectedAutomations,
  selectedAddOns,
  selectedPackage,
  currency,
  rates,
  onReset,
}: PDFExportProps) {
  const [companyName, setCompanyName] = useState("");
  const [isExporting, setIsExporting] = useState(false);
  const [exportError, setExportError] = useState<string | null>(null);

  const fmt = useCallback(
    (usd: number) => formatCurrency(convertCurrency(usd, rates, currency), currency),
    [rates, currency],
  );

  const generateHTML = useCallback(() => {
    const weeklyCost = hours * rate;
    const annualCost = weeklyCost * 52;
    const automatedHours = hours * EFFICIENCY;
    const remainingHours = hours - automatedHours;
    const annualAfter = remainingHours * rate * 52;
    const annualSavings = annualCost - annualAfter;
    const weeklySavings = annualSavings / 52;
    const breakEvenWeeks = weeklySavings > 0 ? Math.ceil(setupCost / weeklySavings) : Infinity;
    const yearOneROI = annualSavings - setupCost;
    const roiPercent = setupCost > 0 ? Math.round((yearOneROI / setupCost) * 100) : 0;

    const selectedAutomationsList = Array.from(selectedAutomations)
      .map((name) => {
        for (const tier of Object.values(TIERS)) {
          const found = tier.automations.find((a) => a.name === name);
          if (found) return { name: found.name, price: found.price };
        }
        return null;
      })
      .filter(Boolean);

    const selectedAddonsList = ADDONS.filter((a) => selectedAddOns.has(a.name));
    const pkg = selectedPackage ? PACKAGES.find((p) => p.name === selectedPackage) : null;

    const title = companyName ? `${companyName} — ROI Report` : "ROI Report";

    return `
      <div style="font-family: 'Inter', -apple-system, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #37322F;">
        <!-- Header -->
        <div style="text-align: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 2px solid #F0EDEB;">
          <h1 style="font-size: 28px; font-weight: 600; margin: 0 0 8px;">${title}</h1>
          <p style="font-size: 14px; color: #605A57; margin: 0;">Generated by FlowAudit_ &bull; ${new Date().toLocaleDateString()}</p>
        </div>

        <!-- ROI Summary -->
        <div style="margin-bottom: 32px;">
          <h2 style="font-size: 18px; font-weight: 600; margin-bottom: 16px;">ROI Summary</h2>
          <table style="width: 100%; border-collapse: collapse;">
            <tr style="border-bottom: 1px solid #F0EDEB;">
              <td style="padding: 8px 0; color: #605A57; font-size: 14px;">Manual Hours/Week</td>
              <td style="padding: 8px 0; text-align: right; font-weight: 600; font-size: 14px;">${hours} hrs</td>
            </tr>
            <tr style="border-bottom: 1px solid #F0EDEB;">
              <td style="padding: 8px 0; color: #605A57; font-size: 14px;">Hourly Rate</td>
              <td style="padding: 8px 0; text-align: right; font-weight: 600; font-size: 14px;">${fmt(rate)}</td>
            </tr>
            <tr style="border-bottom: 1px solid #F0EDEB;">
              <td style="padding: 8px 0; color: #605A57; font-size: 14px;">Annual Cost (Before)</td>
              <td style="padding: 8px 0; text-align: right; font-weight: 600; font-size: 14px;">${fmt(annualCost)}</td>
            </tr>
            <tr style="border-bottom: 1px solid #F0EDEB;">
              <td style="padding: 8px 0; color: #605A57; font-size: 14px;">Annual Cost (After)</td>
              <td style="padding: 8px 0; text-align: right; font-weight: 600; font-size: 14px;">${fmt(annualAfter)}</td>
            </tr>
            <tr style="border-bottom: 1px solid #F0EDEB;">
              <td style="padding: 8px 0; color: #605A57; font-size: 14px;">Annual Savings</td>
              <td style="padding: 8px 0; text-align: right; font-weight: 600; font-size: 14px; color: #059669;">${fmt(annualSavings)}</td>
            </tr>
            <tr style="border-bottom: 1px solid #F0EDEB;">
              <td style="padding: 8px 0; color: #605A57; font-size: 14px;">Setup Investment</td>
              <td style="padding: 8px 0; text-align: right; font-weight: 600; font-size: 14px;">${fmt(setupCost)}</td>
            </tr>
            <tr style="border-bottom: 1px solid #F0EDEB;">
              <td style="padding: 8px 0; color: #605A57; font-size: 14px;">Break-Even</td>
              <td style="padding: 8px 0; text-align: right; font-weight: 600; font-size: 14px;">${breakEvenWeeks === Infinity ? "N/A" : `${breakEvenWeeks} weeks`}</td>
            </tr>
            <tr style="border-bottom: 2px solid #37322F;">
              <td style="padding: 12px 0; font-weight: 600; font-size: 16px;">Year 1 Net ROI</td>
              <td style="padding: 12px 0; text-align: right; font-weight: 700; font-size: 16px; color: ${yearOneROI >= 0 ? "#059669" : "#dc2626"};">${fmt(yearOneROI)} (${roiPercent}%)</td>
            </tr>
          </table>
        </div>

        <!-- Selected Package or Automations -->
        ${
          pkg
            ? `
          <div style="margin-bottom: 32px;">
            <h2 style="font-size: 18px; font-weight: 600; margin-bottom: 16px;">Selected Package: ${pkg.name}</h2>
            <p style="font-size: 14px; color: #605A57;">${pkg.description} — ${fmt(pkg.price)}</p>
            <ul style="margin-top: 8px; padding-left: 20px;">
              ${pkg.features.map((f) => `<li style="font-size: 13px; color: #605A57; margin-bottom: 4px;">${f}</li>`).join("")}
            </ul>
          </div>
        `
            : selectedAutomationsList.length > 0
              ? `
          <div style="margin-bottom: 32px;">
            <h2 style="font-size: 18px; font-weight: 600; margin-bottom: 16px;">Selected Automations (${selectedAutomationsList.length})</h2>
            <table style="width: 100%; border-collapse: collapse;">
              ${selectedAutomationsList.map((a) => (a ? `<tr style="border-bottom: 1px solid #F0EDEB;"><td style="padding: 6px 0; font-size: 13px;">${a.name}</td><td style="padding: 6px 0; text-align: right; font-size: 13px; color: #605A57;">${fmt(a.price)}</td></tr>` : "")).join("")}
            </table>
          </div>
        `
              : ""
        }

        <!-- Add-ons -->
        ${
          selectedAddonsList.length > 0
            ? `
          <div style="margin-bottom: 32px;">
            <h2 style="font-size: 18px; font-weight: 600; margin-bottom: 16px;">Add-On Services</h2>
            <table style="width: 100%; border-collapse: collapse;">
              ${selectedAddonsList.map((a) => `<tr style="border-bottom: 1px solid #F0EDEB;"><td style="padding: 6px 0; font-size: 13px;">${a.name}</td><td style="padding: 6px 0; text-align: right; font-size: 13px; color: #605A57;">${fmt(a.price)}</td></tr>`).join("")}
            </table>
          </div>
        `
            : ""
        }

        <!-- Footer -->
        <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #F0EDEB; text-align: center;">
          <p style="font-size: 12px; color: #605A57;">FlowAudit_ &bull; flowaudit.co.uk &bull; AI Operations Assistants</p>
          <p style="font-size: 11px; color: #605A57; margin-top: 4px;">This report is an estimate. Actual results may vary based on implementation scope.</p>
        </div>
      </div>
    `;
  }, [
    hours,
    rate,
    setupCost,
    selectedAutomations,
    selectedAddOns,
    selectedPackage,
    companyName,
    fmt,
  ]);

  const handleExportPDF = useCallback(async () => {
    setIsExporting(true);
    setExportError(null);
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ unit: "mm", format: "a4", orientation: "portrait" });

      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 20;
      const contentWidth = pageWidth - margin * 2;
      let y = 20;

      // --- Compute all values ---
      const weeklyCost = hours * rate;
      const annualCost = weeklyCost * 52;
      const automatedHours = hours * EFFICIENCY;
      const remainingHours = hours - automatedHours;
      const annualAfter = remainingHours * rate * 52;
      const annualSavings = annualCost - annualAfter;
      const weeklySavings = annualSavings / 52;
      const breakEvenWeeks = weeklySavings > 0 ? Math.ceil(setupCost / weeklySavings) : Infinity;
      const yearOneROI = annualSavings - setupCost;
      const roiPercent = setupCost > 0 ? Math.round((yearOneROI / setupCost) * 100) : 0;

      const selectedAutomationsList = Array.from(selectedAutomations)
        .map((name) => {
          for (const tier of Object.values(TIERS)) {
            const found = tier.automations.find((a) => a.name === name);
            if (found) return { name: found.name, price: found.price };
          }
          return null;
        })
        .filter(Boolean);

      const selectedAddonsList = ADDONS.filter((a) => selectedAddOns.has(a.name));
      const pkg = selectedPackage ? PACKAGES.find((p) => p.name === selectedPackage) : null;

      // --- Helper: check if we need a new page ---
      const checkPage = (needed: number) => {
        if (y + needed > doc.internal.pageSize.getHeight() - 15) {
          doc.addPage();
          y = 20;
        }
      };

      // --- Header ---
      doc.setFont("helvetica", "bold");
      doc.setFontSize(22);
      const title = companyName ? `${companyName} — ROI Report` : "ROI Report";
      doc.text(title, pageWidth / 2, y, { align: "center" });
      y += 8;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(96, 90, 87);
      doc.text(`Generated by FlowAudit_  •  ${new Date().toLocaleDateString()}`, pageWidth / 2, y, {
        align: "center",
      });
      y += 4;

      doc.setDrawColor(240, 237, 235);
      doc.setLineWidth(0.5);
      doc.line(margin, y, pageWidth - margin, y);
      y += 10;

      // --- ROI Summary table ---
      doc.setTextColor(55, 50, 47);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.text("ROI Summary", margin, y);
      y += 8;

      const roiRows: [string, string][] = [
        ["Manual Hours/Week", `${hours} hrs`],
        ["Hourly Rate", fmt(rate)],
        ["Annual Cost (Before)", fmt(annualCost)],
        ["Annual Cost (After)", fmt(annualAfter)],
        ["Annual Savings", fmt(annualSavings)],
        ["Setup Investment", fmt(setupCost)],
        ["Break-Even", breakEvenWeeks === Infinity ? "N/A" : `${breakEvenWeeks} weeks`],
      ];

      doc.setFontSize(10);
      for (const [label, value] of roiRows) {
        checkPage(8);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(96, 90, 87);
        doc.text(label, margin, y);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(55, 50, 47);
        doc.text(value, pageWidth - margin, y, { align: "right" });
        y += 2;
        doc.setDrawColor(240, 237, 235);
        doc.line(margin, y, pageWidth - margin, y);
        y += 6;
      }

      // Year 1 Net ROI (bold, larger)
      checkPage(12);
      doc.setDrawColor(55, 50, 47);
      doc.setLineWidth(0.8);
      doc.line(margin, y - 2, pageWidth - margin, y - 2);
      y += 2;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(55, 50, 47);
      doc.text("Year 1 Net ROI", margin, y);
      doc.setTextColor(
        yearOneROI >= 0 ? 5 : 220,
        yearOneROI >= 0 ? 150 : 38,
        yearOneROI >= 0 ? 105 : 38,
      );
      doc.text(`${fmt(yearOneROI)} (${roiPercent}%)`, pageWidth - margin, y, { align: "right" });
      y += 12;

      // --- Selected Package or Automations ---
      if (pkg) {
        checkPage(20);
        doc.setTextColor(55, 50, 47);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(14);
        doc.text(`Selected Package: ${pkg.name}`, margin, y);
        y += 7;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.setTextColor(96, 90, 87);
        const descLines = doc.splitTextToSize(
          `${pkg.description} — ${fmt(pkg.price)}`,
          contentWidth,
        );
        doc.text(descLines, margin, y);
        y += descLines.length * 5 + 3;

        for (const feature of pkg.features) {
          checkPage(6);
          doc.text(`•  ${feature}`, margin + 4, y);
          y += 5;
        }
        y += 5;
      } else if (selectedAutomationsList.length > 0) {
        checkPage(20);
        doc.setTextColor(55, 50, 47);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(14);
        doc.text(`Selected Automations (${selectedAutomationsList.length})`, margin, y);
        y += 8;

        doc.setFontSize(10);
        for (const item of selectedAutomationsList) {
          if (!item) continue;
          checkPage(8);
          doc.setFont("helvetica", "normal");
          doc.setTextColor(55, 50, 47);
          doc.text(item.name, margin, y);
          doc.setTextColor(96, 90, 87);
          doc.text(fmt(item.price), pageWidth - margin, y, { align: "right" });
          y += 2;
          doc.setDrawColor(240, 237, 235);
          doc.setLineWidth(0.3);
          doc.line(margin, y, pageWidth - margin, y);
          y += 5;
        }
        y += 3;
      }

      // --- Add-On Services ---
      if (selectedAddonsList.length > 0) {
        checkPage(20);
        doc.setTextColor(55, 50, 47);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(14);
        doc.text("Add-On Services", margin, y);
        y += 8;

        doc.setFontSize(10);
        for (const addon of selectedAddonsList) {
          checkPage(8);
          doc.setFont("helvetica", "normal");
          doc.setTextColor(55, 50, 47);
          doc.text(addon.name, margin, y);
          doc.setTextColor(96, 90, 87);
          doc.text(addon.price > 0 ? fmt(addon.price) : "Get a Quote", pageWidth - margin, y, {
            align: "right",
          });
          y += 2;
          doc.setDrawColor(240, 237, 235);
          doc.setLineWidth(0.3);
          doc.line(margin, y, pageWidth - margin, y);
          y += 5;
        }
        y += 3;
      }

      // --- Footer ---
      checkPage(20);
      doc.setDrawColor(240, 237, 235);
      doc.setLineWidth(0.5);
      doc.line(margin, y, pageWidth - margin, y);
      y += 8;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(96, 90, 87);
      doc.text("FlowAudit_  •  flowaudit.co.uk  •  AI Operations Assistants", pageWidth / 2, y, {
        align: "center",
      });
      y += 5;
      doc.setFontSize(8);
      doc.text(
        "This report is an estimate. Actual results may vary based on implementation scope.",
        pageWidth / 2,
        y,
        { align: "center" },
      );

      doc.save(`${companyName || "FlowAudit_"}-ROI-Report.pdf`);
    } catch (error) {
      console.error("PDF export failed:", error);
      setExportError(
        error instanceof Error
          ? error.message
          : "PDF export failed. Try using Print Report instead.",
      );
    } finally {
      setIsExporting(false);
    }
  }, [
    hours,
    rate,
    setupCost,
    selectedAutomations,
    selectedAddOns,
    selectedPackage,
    companyName,
    fmt,
  ]);

  const handlePrint = useCallback(() => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) {
      // Popup blocked — fall back to printing current page
      window.print();
      return;
    }
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>FlowAudit_ ROI Report</title>
          <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
        </head>
        <body style="margin: 0; padding: 20px;">
          ${generateHTML()}
          <script>window.onload = function() { window.print(); }<\/script>
        </body>
      </html>
    `);
    printWindow.document.close();
  }, [generateHTML]);

  return (
    <div className="rounded-2xl border border-[rgba(55,50,47,0.08)] bg-white p-6">
      <h3 className="mb-1 font-sans text-sm font-semibold text-[#37322F]">Export Report</h3>
      <p className="mb-4 font-sans text-xs text-[#605A57]">
        Your personalized report, ready to share with your team.
      </p>
      <div className="space-y-3">
        <input
          type="text"
          placeholder="Company name (optional)"
          value={companyName}
          onChange={(e) => setCompanyName(e.target.value)}
          className="w-full rounded-lg border border-[rgba(55,50,47,0.12)] bg-white px-3 py-2 font-sans text-sm text-[#37322F] placeholder:text-[#605A57]/50 focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/30 focus:outline-none"
        />
        <div className="flex gap-2">
          <Button
            onClick={handleExportPDF}
            disabled={isExporting}
            className="flex-1 bg-emerald-600 text-white hover:bg-emerald-700"
          >
            <FileDown className="mr-2 h-4 w-4" />
            {isExporting ? "Exporting..." : "Export PDF"}
          </Button>
          <Button onClick={handlePrint} variant="secondary" className="flex-1">
            <Printer className="mr-2 h-4 w-4" />
            Print Report
          </Button>
        </div>
        {exportError && <p className="font-sans text-xs text-red-600">{exportError}</p>}
        <Button
          variant="ghost"
          className="w-full border border-dashed border-[rgba(55,50,47,0.2)]"
          onClick={() => {
            onReset();
            setCompanyName("");
          }}
        >
          <RotateCcw className="mr-2 h-4 w-4" />
          Reset Calculator
        </Button>
      </div>
    </div>
  );
}

export { PDFExport };
